### ISSUE TITLE
postinstall fails in noexec enviornment

### ISSUE THREAD

**Issue by rozwell** [WebReflection/document-register-element#184]
On a noexec filesystem you need to specify interpreter, in our case it's node, otherwise it will result in errors like this one:

```
verbose 59.278636019 Error: /project/node_modules/document-register-element: Command failed.
Exit code: 126
Command: lightercollective
Arguments:
Directory: /project/node_modules/document-register-element
Output:
/bin/sh: /project/node_modules/document-register-element/node_modules/.bin/lightercollective: Permission denied
    at ProcessTermError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/share/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/usr/share/yarn/lib/cli.js:25884:17)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
error /project/node_modules/document-register-element: Command failed.
Exit code: 126
Command: lightercollective
Arguments:

```

Fixed in #183

**Comment by WebReflection** [comment]
MR accepted, thanks!
