### ISSUE TITLE
Import fails when using node >= 7.3.0

### ISSUE THREAD

**Issue by steabert** [WebReflection/document-register-element#98]
Importing document-register-element in node fails with:

```
TypeError: Cannot assign to read only property 'prototype' of function 'class HTMLCollection {
      constructor(secret, element, query) {
        if (secret !== privates) {
          throw new T...<omitted>...
    }'
      
      at patchClass (../node_modules/document-register-element/build/document-register-element.node.js:1370:34)
      at polyfillV1 (../node_modules/document-register-element/build/document-register-element.node.js:1382:7)
      at installCustomElements (../node_modules/document-register-element/build/document-register-element.node.js:1393:48)
      at Object.<anonymous> (../node_modules/document-register-element/build/document-register-element.node.js:1433:1)
```

This seems to be because of: https://github.com/nodejs/node/commit/524f693872cf453af2655ec47356d25d52394e3d

They might revert it in Node: https://github.com/nodejs/node/pull/10920

Anyway, I thought I would mention this, since currently import fails when using Node 7.3.0 and 7.4.0.

**Comment by WebReflection** [comment]
wait ... what has this library to do with NodeJS exactly? I'm not sure I understand your heads up (thanks though)

**Comment by steabert** [comment]
Well, we use it with node, we are running tests with jest/jsdom. But yes, as you say, this isn't really your problem.
